### ISSUE TITLE
Table columns named "name" can not be defined in the table configs

### ISSUE THREAD

**Issue by kschweiger** [kschweiger/data_organizer#7]
```toml
[main]
    name="main"
    [main.id]
        ctype="SERIAL"
        is_primary=true
    [main.name]
        ctype="TEXT"
```

Issue `name="main"` and  `[main.name]` are the same :unamused:
